export { default as Player } from './player';
export { default as FallBlock } from './fallblock';
export { default as JumpBlock } from './jumpblock';
export { default as Spike } from './spike';
export { default as Splash } from './splash';
export { default as ColorBlock } from './colorblock';
export { default as Collectible } from './collectible';
export { default as Spider } from './spider';
export { default as BgDrop } from './bgdrop';
